### ISSUE TITLE
SALTS ERROR on startup of KODI

### ISSUE THREAD

**Issue by cynical66** [tknorris/tknorris-beta-repo#43]
As soon as I start up my devices, it gives a SALTS error - "stream all the sources error check the log for more information" and won't allow me to access SALTS any longer. I am using 2.0.85

**Comment by tknorris** [comment]
Post a log.

**Comment by cynical66** [comment]
ok, I will have to post it when I get home tonight. Is there somewhere I can learn to do that easily? Thanke for the help!!

**Comment by tknorris** [comment]
https://www.tvaddons.ag/posting-error-logs-kodi/

**Comment by cynical66** [comment]
will do. I will as soon as i get home. again, thanks for your help!

**Comment by cynical66** [comment]
here is the log

https://logs.tvaddons.ag/p7jgpawyv

**Comment by tknorris** [comment]
You are running an outdated urlresolver. Do a SYSTEM->Settings->Addons->Left Menu->Check for updates. Also, STRONGLY consider uninstalled some of the repositories you have installed. You are just asking for trouble w/ that many repos installed. Also, consider upgrading to 16.1 of Kodi rather than BETA3. You shouldn't run a beta version for long term use.

If the check for updates doesn't work, you can install the latest urlresolver from [fusion](http://fusion.tvaddons.ag/xbmc-scripts/).

**Comment by cynical66** [comment]
Follow up question:
You recommended installing the latest urlresolver from fusion. I am lost on this. I have tried and got error messages. The only thing that fixed it so far (and probably temp) is I updated urlresolver to an older version. Tips, help? 

Thanks again for all you do here man!

**Comment by tknorris** [comment]
Follow this. The problem is [different](https://github.com/tknorris/tknorris-beta-repo/wiki/SALTS---Frequently-Asked-Questions#i-see-some-kind-of-error-in-the-log-about-no-module-named-urlresolver-or-a-similar-urlresolver-error), but the solution is the same.
