### ISSUE TITLE
Url Resolver not working on Mac with Krypton 17 Beta

### ISSUE THREAD

**Issue by Bigperm1** [tknorris/tknorris-beta-repo#45]
https://ares-project.uk/logupload/log.php?id=43639

**Comment by tknorris** [comment]
That is an SSL validation issue. You are either missing some certificate authorities, or the website doesn't have a proper SSL certificate, or you're being bitten by the big that openssl validates SSL certificates slightly differently than your browser does which causes some certs to fail that work in the browser. You can work around the problem by disabling certificate validation but that is only a temporary fix since cert validation is an important part of SSL.

To do that, add the following lines at the top of /script.module.urlresolver/tree/master/lib/urlresolver/lib/net.py

```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

While this will stop the error, we can't view it as an actual solution because I don't want to remove certificate validation from urlresolver completely since it works for most people and is pretty important.
